client:
  cache: null
  domain: []
  impl: api
  postman:
    meta_data:
      headers: null
      impersonate: chrome110
      proxies:
        http: 127.0.0.1:10810
        https: 127.0.0.1:10810
    type: cffi
  retry_times: 5
dir_rule:
  base_dir: ./download
  rule: Bd_Aid_Pindex
download:
  cache: true
  image:
    decode: true
    suffix: .jpg
  threading:
    image: 30
    photo: 4
log: true
plugins:
  valid: log
version: '2.1'
